matchBlocks=sculk smooth_basalt tuff obsidian snow_block blue_ice dripstone_block sulfur cinnabar grass_block clay emerald_ore lapis_ore coal_ore gold_ore redstone_ore diamond_ore iron_ore copper_ore bedrock stone coarse_dirt sand red_sand podzol mycelium sandstone red_sandstone granite diorite andesite terracotta white_terracotta orange_terracotta magenta_terracotta light_blue_terracotta yellow_terracotta lime_terracotta pink_terracotta gray_terracotta light_gray_terracotta cyan_terracotta purple_terracotta blue_terracotta brown_terracotta green_terracotta red_terracotta black_terracotta suspicious_gravel suspicious_sand
method=overlay
tiles=0-16
faces=top bottom
connect=block
connectBlocks=deepslate:axis=y deepslate_coal_ore deepslate_iron_ore deepslate_gold_ore deepslate_redstone_ore deepslate_diamond_ore deepslate_emerald_ore deepslate_lapis_ore
layer=cutout_mipped
